### PR TITLE
Tg/#1 Home Page

### PR DESCRIPTION
**Pull request by tugberkgoc**
[Quick Explanation] "/.nuxt" folder is created automatically, when we run `nuxt build && npm run build`.
I have added that folder, you do not need to run again this command. You can run `npm start` to start the project.

[Suggestion] If you want to look at the code that I have written, we should delete the "/.nuxt" folder and add to .gitignore as ignored folder, so you can easily manage to inspect what I have changed in the code.

If you have any issues, please write me from here, I will look at real quick. Thanks, Tugberk.

### CODE REVIEW

**Comment by davidgatti** [comment]
- code looking good
- no need to include the build content, please never add that folder and the dist folder
- the site will be alwasy generated since it needs to be visible to google
- We need to add placeholders. if you check the original HTML page you will find {{SOME VALUE}} - this are placeholders in our new case we just need to add in the HTML the string `REPLACE_ME` to let people know this values needs to be replaced manually.

**Comment by tugberkgoc** [comment]
> * code looking good
> * no need to include the build content, please never add that folder and the dist folder
> * the site will be alwasy generated since it needs to be visible to google
> * We need to add placeholders. if you check the original HTML page you will find {{SOME VALUE}} - this are placeholders in our new case we just need to add in the HTML the string `REPLACE_ME` to let people know this values needs to be replaced manually.
> 
> # Question
> right now the JS code with the AWS SDK is on one page, but all other pages will need the AWS SDK to be globally available despite this is a single page, can you set the code in a way that the AWS SDK is always globally available?

Thank you so much for the compliment. It is really important to hear your thoughts for me.

I have fixed the issue that including build content. You can check from [here](https://github.com/0x4447-bootstrap/0x4447_bootstrap_placeholder_webpage/pull/1/commits/e77e6b0573f96dc9dd4f66dce3d42fa0048dcdc8).

Also, I have done the implementation of placeholders. You can check from [here](https://github.com/0x4447-bootstrap/0x4447_bootstrap_placeholder_webpage/pull/1/commits/e77e6b0573f96dc9dd4f66dce3d42fa0048dcdc8).

You are right about setting AWS as globally. I have done the implementation, you can check from [here](https://github.com/0x4447-bootstrap/0x4447_bootstrap_placeholder_webpage/pull/1/commits/a8e9ccba91bdfddc1568dc39f5360da4e40b98db).

I have a question about "the site will be always generated since it needs to be visible to google".
Does it mean, we will build nuxt project as static pages. Can you explain it to me. I just want to make sure that I understand clearly.

**Comment by davidgatti** [comment]
Yes this page will be statically generated, uploaded to S3, and delivered over CloudFront.

**Comment by tugberkgoc** [comment]
Can you check the branch? Is there any issues, please let me know, I will quickly help.

**Comment by davidgatti** [comment]
@tugberkgoc I think this folder and files should be ignored and not committed `.idea/workspace.xml`

**Comment by tugberkgoc** [comment]
Yes, you are right. I have deleted .idea folder and .DS_Store document, now.

**Comment by davidgatti** [comment]
Well you also have to remove the folder and all the files from the git cashe `.idea/workspace.xml` this file is still present.

**Pull request merged**
